project:
  type: website
  output-dir: docs

website:
  title: "MarikoBron.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Project_page.qmd
      - freeforall_page.qmd
      - resume_page.qmd
      - aus_creatures.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

