project:
  type: website
  output-dir: docs

website:
  title: "MarikoBron.github.io"
  favicon: photos/weevlogo.png 
  navbar:
    title: false
    logo: photos/weevlogo.png
    logo-alt: "weevil logo"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Project_page.qmd
      - freeforall_page.qmd
      - resume_page.qmd
      - aus_creatures.qmd
      
format:
  html:
    theme: 
      - styles.scss
      - cosmo
    toc: true

editor: visual

